OPENAI_API_KEY = "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"

[connections.snowpark]
user = "streamlit"
password = "OpeAi@Np#1"
warehouse = "DEMO_WH"
role = "S05_READONLY_ROLE"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "NETAPP_PROD.west-us-2.azure"